### ISSUE TITLE
Inkpad Color 3 USB device ids not recognized

### ISSUE THREAD

**Issue by poebel** [zisoft/calibre-pocketbook-device-driver#4]
Would you be able to add support for those ids to your driver?

From the calibre logs:
` USBDevice(vendor_id=0x1d6b product_id=0x104 bcd=0x100 devid=usb\vid_1d6b&pid_0104&rev_0100 devinst=10),`

Please note that those ids seem to be also used by the Bookeen Diva HD, by default the Inkpad Color 3 is therefore detected as a Diva HD.

**Comment by zisoft** [comment]
I have no way to test this so can you please try the following:

- Download [pocketbook632.zip](https://github.com/zisoft/calibre-pocketbook-device-driver/releases/download/v1.0.3/pocketbook632.zip) and unpack the zip file
- Open `device.py` in an editor and edit the lines 51-54 to add the information for the device
- pack the files again into the zip and install this zip in calibre as described in the README

Please report back here if that works.

**Comment by poebel** [comment]
Works fine, I've created a merge request with the changes.
